[[redirects]]
  from = "/home"
  to = "/Home"

[[redirects]]
  from = "/products"
  to = "/products"

[[redirects]]
  from = "/about"
  to = "https://delitestdeploy.netlify.app/about"

[[redirects]]
  from = "/detail/*"
  to = "/detail/:splat"

[[redirects]]
  from = "/blog"
  to = "/Blog"

[[redirects]]
  from = "/carrito"
  to = "/Carrito"

[[redirects]]
  from = "/admin"
  to = "/DashboardAdmin"